<option value="">Jour</option>
<option value="1" 	<?php if ( $p['jour'] == "1"	)		{ echo 'selected="selected"'; }	?> 		>1</option>
<option value="2"	<?php if ( $p['jour'] == "2"	)		{ echo 'selected="selected"'; }	?>   	>2</option>
<option value="3" 	<?php if ( $p['jour'] == "3"	)		{ echo 'selected="selected"'; }	?>   	>3</option>
<option value="4" 	<?php if ( $p['jour'] == "4"	)		{ echo 'selected="selected"'; }	?>   	>4</option>
<option value="5" 	<?php if ( $p['jour'] == "5"	)		{ echo 'selected="selected"'; }	?>   	>5</option>
<option value="6" 	<?php if ( $p['jour'] == "6"	)		{ echo 'selected="selected"'; }	?>   	>6</option>
<option value="7" 	<?php if ( $p['jour'] == "7"	)		{ echo 'selected="selected"'; }	?>   	>7</option>
<option value="8" 	<?php if ( $p['jour'] == "8"	)		{ echo 'selected="selected"'; }	?>   	>8</option>
<option value="9" 	<?php if ( $p['jour'] == "9"	)		{ echo 'selected="selected"'; }	?> 		>9</option>
<option value="10" 	<?php if ( $p['jour'] == "10"	)		{ echo 'selected="selected"'; }	?>   	>10</option>
<option value="11" 	<?php if ( $p['jour'] == "11"	)		{ echo 'selected="selected"'; }	?> 		>11</option>
<option value="12" 	<?php if ( $p['jour'] == "12"	)		{ echo 'selected="selected"'; }	?> 		>12</option>
<option value="13" 	<?php if ( $p['jour'] == "13"	)		{ echo 'selected="selected"'; }	?> 		>13</option>
<option value="14"	<?php if ( $p['jour'] == "14"	)		{ echo 'selected="selected"'; }	?>   	>14</option>
<option value="15"	<?php if ( $p['jour'] == "15"	)		{ echo 'selected="selected"'; }	?>   	>15</option>
<option value="16" 	<?php if ( $p['jour'] == "16"	)		{ echo 'selected="selected"'; }	?>   	>16</option>
<option value="17" 	<?php if ( $p['jour'] == "17"	)		{ echo 'selected="selected"'; }	?>   	>17</option>
<option value="18" 	<?php if ( $p['jour'] == "18"	)		{ echo 'selected="selected"'; }	?>   	>18</option>
<option value="19" 	<?php if ( $p['jour'] == "19"	)		{ echo 'selected="selected"'; }	?>   	>19</option>
<option value="20" 	<?php if ( $p['jour'] == "20"	)		{ echo 'selected="selected"'; }	?>   	>20</option>
<option value="21" 	<?php if ( $p['jour'] == "21"	)		{ echo 'selected="selected"'; }	?> 		>21</option>
<option value="22" 	<?php if ( $p['jour'] == "22"	)		{ echo 'selected="selected"'; }	?> 		>22</option>
<option value="23" 	<?php if ( $p['jour'] == "23"	)		{ echo 'selected="selected"'; }	?> 		>23</option>
<option value="24"	<?php if ( $p['jour'] == "24"	)		{ echo 'selected="selected"'; }	?>   	>24</option>
<option value="25" 	<?php if ( $p['jour'] == "25"	)		{ echo 'selected="selected"'; }	?>   	>25</option>
<option value="26" 	<?php if ( $p['jour'] == "26"	)		{ echo 'selected="selected"'; }	?>   	>26</option>
<option value="27" 	<?php if ( $p['jour'] == "27"	)		{ echo 'selected="selected"'; }	?>   	>27</option>
<option value="28" 	<?php if ( $p['jour'] == "28"	)		{ echo 'selected="selected"'; }	?>   	>28</option>
<option value="29" 	<?php if ( $p['jour'] == "29"	)		{ echo 'selected="selected"'; }	?>   	>29</option>
<option value="30" 	<?php if ( $p['jour'] == "30"	)		{ echo 'selected="selected"'; }	?>   	>30</option>
<option value="31" 	<?php if ( $p['jour'] == "31"	)		{ echo 'selected="selected"'; }	?> 		>31</option>